version: '3.8'

services:
  storybook:
    build:
      context: ..  # Build from parent directory to access components
      dockerfile: storybook-demo/Dockerfile
    container_name: nuralyui-storybook
    ports:
      - "6001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - storybook-network

  # Optional: Add a reverse proxy for SSL and domain management
  nginx-proxy:
    image: nginx:alpine
    container_name: storybook-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - storybook
    networks:
      - storybook-network
    profiles:
      - production

networks:
  storybook-network:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  storybook-data:
    driver: local
