version: '3.8'

services:
  storybook:
    build:
      context: ..  # Build from parent directory to access components
      dockerfile: storybook-demo/Dockerfile
    container_name: nuralyui-storybook
    ports:
      - "6001:80"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - storybook-network

networks:
  storybook-network:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  storybook-data:
    driver: local
