version: '3.8'

services:
  storybook-dev:
    build:
      context: ..  # Build from parent directory to access components
      dockerfile: storybook-demo/Dockerfile.dev
    container_name: nuralyui-storybook-dev
    ports:
      - "6006:6006"
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/storybook-demo/node_modules
    environment:
      - NODE_ENV=development
    command: npm run storybook
    working_dir: /app/storybook-demo
    networks:
      - storybook-network

networks:
  storybook-network:
    driver: bridge
